id: P010802
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN8173
  title: དྲིན་ལན་བསབ་པའི་མདོ།
  author: ''
  volumes:
    a44a5deac7094967a378737415550fe9:
      image_group_id: I3CN8175
      title: ''
      volume_number: 1
      total_pages: 418
      base_file: v001.txt
